// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarageNA20.Data;

namespace StarageNA20.Migrations
{
    [DbContext(typeof(StarageNA20Context))]
    [Migration("20200429115019_AddCategory")]
    partial class AddCategory
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StarageNA20.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Shelf")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Mobile",
                            Count = 156,
                            Description = "Stupid",
                            Name = "Iphone",
                            OrderDate = new DateTime(2020, 4, 23, 13, 50, 19, 282, DateTimeKind.Local).AddTicks(3991),
                            Price = 15600,
                            Shelf = "4B"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Mobile",
                            Count = 98,
                            Description = "Better",
                            Name = "S10",
                            OrderDate = new DateTime(2020, 4, 6, 13, 50, 19, 286, DateTimeKind.Local).AddTicks(1528),
                            Price = 12450,
                            Shelf = "4C"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Computers",
                            Count = 23,
                            Description = "Stupid",
                            Name = "MacBook",
                            OrderDate = new DateTime(2020, 4, 24, 13, 50, 19, 286, DateTimeKind.Local).AddTicks(1596),
                            Price = 45600,
                            Shelf = "4C"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Computer",
                            Count = 32,
                            Description = "Stupid",
                            Name = "Suface X",
                            OrderDate = new DateTime(2020, 3, 20, 13, 50, 19, 286, DateTimeKind.Local).AddTicks(1603),
                            Price = 26850,
                            Shelf = "5C"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Office Supplies",
                            Count = 15651,
                            Description = "Stupid",
                            Name = "Pen",
                            OrderDate = new DateTime(2020, 4, 23, 13, 50, 19, 286, DateTimeKind.Local).AddTicks(1607),
                            Price = 1,
                            Shelf = "45W"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
